### PR TITLE
Update projects info

### PR DESCRIPTION
**Pull request by calvellido**
This PR updates 47 Degrees OSS projects info.

### CODE REVIEW

**Comment by cb372** [comment]
@calvellido I noticed today that the org site is pretty broken since we moved the open-source repos to the 47degrees organization. I start fixing it but then I found this PR.

Do you have time to work on this? If not, do you mind if I pick it up?

**Comment by calvellido** [comment]
Woops!  Sure @cb372!  I started working on this but then pandemic happened, and between that and client work I totally forgot this.

Let me know if I can help on anything, many thanks!

**Comment by cb372** [comment]
I made a few more updates to the list of projects and fixed all the logos. This is now ready for review.

**Comment by cb372** [comment]
Screenshot 2020-05-27 at 16 48 12
Screenshot 2020-05-27 at 16 48 20
Screenshot 2020-05-27 at 16 48 27

Note: `iota` and `org` do not have logos, as far as I can tell.

**Review by cb372 — APPROVED** [review]
Just noticed I didn't open this PR so I can approve it myself 💪

**Pull request merged**
