### PR TITLE
Fixed footer with a link to `org`

### PR DESCRIPTION
**Pull request by ghost**
Addresses #34

### CODE REVIEW

**Comment by MaureenElsberry** [comment]
If I'm reading this correctly @dialelo, if my organization's name was Moth Balls, my footer would be configured as:

Copyright 2017 Moth Balls - Built with org       Is that correct?

What about doing:

Copyright 2017 Moth Balls - Built with org by 47 Degrees     or do you guys think that is too aggressive looking?

**Comment by ghost** [comment]
>If I'm reading this correctly @dialelo, if my organization's name was Moth Balls, my footer would be configured as:

>Copyright 2017 Moth Balls - Built with org Is that correct?

Yes!

>What about doing:

>Copyright 2017 Moth Balls - Built with org by 47 Degrees or do you guys think that is too aggressive looking?

I think is fine, I can add a config option for hiding the "by 47 Degrees" if people want to turn it off.

**Comment by MaureenElsberry** [comment]
SGTM!

**Comment by ghost** [comment]
Done, and turned it on by default.

by

**Review by raulraja — APPROVED** [review]

**Comment by ghost** [comment]
Take a look @MaureenElsberry.

**Review by MaureenElsberry — APPROVED** [review]
LGTM!

**Pull request merged**
