### PR TITLE
Add scala-exercises

### LINKED ISSUE #5: Project whitelist
We need to create the list with the repos we want to see in our open source page.

### PR DESCRIPTION
**Pull request by ghost**
I added a new setting, `:extra-repos`, for including projects outside of the organization.

- [x] Do we want to add any repo in the `scala-exercises` org beside the main one @raulraja ?

Nice boost of stats from adding scala-exercises, before:

before

After:

after

- [x] The logo has a light hexagon that is not visible due to the background, @israelperezglez we may want to make a dark version.

scex

Closes #5

### CODE REVIEW

**Comment by raulraja** [comment]
Awesome, yeah that one is fine for now and we will add more down the road for the evaluator and others.

**Comment by raulraja** [comment]
LGTM!

**Comment by israelperezglez** [comment]
@dialelo I will send you the dark logo version ;)

**Comment by MaureenElsberry** [comment]
yay! Thanks @dialelo @raulraja  - I think that's our most well known open source project so it'd be a shame if it wasn't featured - but looks great and excited it worked out! Thanks!!!!

**Comment by raulraja** [comment]
Before we do any marketing target to the 47deg org we need to ensure it's published as described in https://github.com/47deg/org/issues/23

**Comment by raulraja** [comment]
LGTM, merge at will once you get heat you need from @israelperezglez

**Comment by israelperezglez** [comment]
@dialelo @raulraja I attach the Scala Exercise logo in dark version (88x88 // .png)

logo_scala_exercises_dark_version

**Comment by ghost** [comment]
Thanks @israelperezglez !

**Pull request merged**
